### ISSUE TITLE
How does it work in leak data?

### ISSUE THREAD

**Issue by cjc-github** [Trustworthy-Software/RAICC#2]
Could you give me an example of RAICC to leak information? of course, the leak information cannot be found by Flowdroid(Iccta) or Amandroid.  I trust send and sendIntent in RAICC/artefacts/droidbench/apks/ ，but all these leak can be found by Amandroid. I hope you can relpy to me,Thank you very much.

**Comment by JordanSamhi** [comment]
Hello @cjc-github,

RAICC does not leak information but whether detect apps that can leak data in unexpected/atypical ways.
You can find an example here: https://github.com/Trustworthy-Software/RAICC/tree/master/artefacts/droidbench/sources/sendTextMessage1/main/java/lu/uni/trux/raicc/sendTextMessage1
From MainActivity to TargetActivity, the IMEI number will be leaked, RAICC detects that.

I am not sure I understand your second concern , there is no leak in send or sendIntent apps. Could you elaborate?

**Comment by cjc-github** [comment]
That's my problem.I thought the AICC could be used to leak sensitive information without  being detected by Amandroid or Flowdroid until you reply.I am so sorry that statement may be not clear.

**Comment by JordanSamhi** [comment]
Actually, yes AICC can be used to leak information without being detected by Flowdroid or Amandroid, you can see the example here: https://github.com/Trustworthy-Software/RAICC/tree/master/artefacts/droidbench/sources/sendTextMessage1/main/java/lu/uni/trux/raicc/sendTextMessage1

Do not confuse AICC with RAICC. RAICC is the tool that detects AICC. AICC can be used to leak sensitive information without being detected by Amandroid or Flowdroid.

**Comment by cjc-github** [comment]
Thanks a lot.
